image: Visual Studio 2017

before_build:
  - .paket\paket.exe restore
  - dotnet restore
  - ps: gitversion /l console /output buildserver

build_script:
  - ps: .\build.ps1 -Target CI -verbosity Verbose -configuration Release
  - msbuild /t:Pack UriTemplateString.sln /p:Configuration=Release
  
test: off

artifacts:
  - path: 'nugets\*.nupkg'
  - path: coverage
    type: zip

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true